name: Expression Lab

on: 
  workflow_dispatch:

env:
  APP_NAME: expression-lab
  APP_ENV: dev

jobs:
  expression-test:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4
       - name: Expression vs shell test
         run: | 
           echo "Expression style: ${{ env.APP_NAME }}"
           echo "shell style: $APP_NAME"

       - name: context test 
         run: |
           echo "Actor: ${{ github.actor }}"
           echo "Branch: ${{ github.ref_name }}"
  
